name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  security-and-build-checks:
    name: Security and Build Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: infra/environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infra/environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra/environments/dev
        run: terraform validate

      - name: Run tfsec IaC Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra

      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          framework: terraform

      - name: Build Docker Image
        run: docker build -t production-pipeline-app ./app

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: production-pipeline-app
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL